config/routes.rb
Aceim::Application.routes.draw do

  resources :archivos

  resources :material_apoyo

  resources :tipo_actividades do
    resources :actividades
  end

  resources :parte_examenes do
    resources :parte_examen_actividades
  end

  resources :parte_examen_actividades do
    resources :actividades
  end

  resources :estudiante_examenes

  resources :examenes do
    resources :parte_examenes
    resources :estudiante_examenes
  end

  resources :actividades do
    resources :preguntas
    resources :textos
    resources :adjuntos    
  end

  resources :preguntas do
    resources :opciones
    resources :respuestas
  end

  resources :opciones

  resources :respuestas

  resources :textos

  resources :adjuntos

  resources :facturas do
    resources :detalle_facturas

    collection do
      get 'nueva'
      post 'actualizar'
      get 'registrar'
      get 'actualizar_idioma_select'
    end
  end
  

   root :to => 'inicio#index'
   
   

  match ':controller(/:action(/:id(.:format)))'
end

app/models/material_apoyo.rb
class MaterialApoyo < ActiveRecord::Base
# ATRIBUTOS ACCESIBLES 
	attr_accessible :id, :nombre, :url, :tipo_material_apoyo_id

# ASOCIACIONES
	has_many :material_apoyo_cursos, :dependent => :destroy, :foreign_key => :material_apoyo_id
	accepts_nested_attributes_for :material_apoyo_cursos

	belongs_to :tipo_material_apoyo,
		:foreign_key => :tipo_material_apoyo_id


end

app/controllers/material_apoyo_controller.rb
class MaterialApoyoController < ApplicationController
  # GET /material_apoyos
  # GET /material_apoyos.json
  before_filter :filtro_logueado
  before_filter :filtro_administrador


  def index
    @material_apoyos = MaterialApoyo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @material_apoyos }
    end
  end

  # GET /material_apoyos/1
  # GET /material_apoyos/1.json
  def show
    @material_apoyo = MaterialApoyo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @material_apoyo }
    end
  end

  # GET /material_apoyos/new
  # GET /material_apoyos/new.json
  def new
    @material_apoyo = MaterialApoyo.new
    @cursos = Curso.where(:tipo_categoria_id => 'AD').order(:grado).delete_if{|c| c.tipo_nivel_id.eql? "CC" or c.tipo_nivel_id.eql? "NI" or c.tipo_nivel_id.eql? "BBVA";}.sort_by{|c| "#{c.idioma_id} #{c.grado}"}
    # @tipo_material_apoyo = all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @material_apoyo }
    end
  end

  # GET /material_apoyos/1/edit
  def edit
    @material_apoyo = MaterialApoyo.find(params[:id])
    @cursos = Curso.where(:tipo_categoria_id => 'AD').order(:grado).delete_if{|c| c.tipo_nivel_id.eql? "CC" or c.tipo_nivel_id.eql? "NI" or c.tipo_nivel_id.eql? "BBVA";}.sort_by{|c| "#{c.idioma_id} #{c.grado}"}    
  end

  # POST /material_apoyos
  # POST /material_apoyos.json
  def create
    @material_apoyo = MaterialApoyo.new(params[:material_apoyo])
    begin
      data = params[:archivo][:datafile]
      ext = data.original_filename.split('.').last
      nombre = "material_apoyo_#{@material_apoyo.id}.#{ext}"
      archivo = "#{Rails.root}/attachments/material_apoyo/#{nombre}"

      @material_apoyo.nombre = nombre
      @material_apoyo.tipo_material_apoyo_id = 'TEXT'
      @material_apoyo.nombre_original = data.original_filename
      @material_apoyo.url = archivo
      data = data.tempfile
      File.open("#{archivo}", "wb") {|file| file.write data.read; file.close}
      if @material_apoyo.save
        flash[:mensaje] += "Material de apoyo Agregado"
        params[:cursos_ids].each_key do |curso_id| 
          idioma_id,tipo_categoria_id,tipo_nivel_id = curso_id.split ","
          MaterialApoyoCurso.create(:material_apoyo_id => @material_apoyo.id, :curso_idioma_id => idioma_id, :curso_tipo_categoria_id => tipo_categoria_id, :curso_tipo_nivel_id => tipo_nivel_id)
        end
      end 
    rescue Exception => e
      flash[:mensaje] = "Error: #{e.message}"
    end
    redirect_to :action => 'index'
  end

  # PUT /material_apoyos/1
  # PUT /material_apoyos/1.json
  def update
    @material_apoyo = MaterialApoyo.find(params[:id])

    respond_to do |format|
      if @material_apoyo.update_attributes(params[:material_apoyo])
        format.html { redirect_to @material_apoyo, notice: 'Material apoyo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @material_apoyo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_apoyos/1
  # DELETE /material_apoyos/1.json
  def destroy
    @material_apoyo = MaterialApoyo.find(params[:id])

    begin
      File.delete(@material_apoyo.url)
      @material_apoyo.destroy
      flash[:mensaje] = "Archivo Eliminado del sistema."
    rescue Exception => e
      flash[:mensaje] = "Error al intentar eliminar. #{e.message}"
    end
    respond_to do |format|
      format.html { redirect_to material_apoyos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/material_apoyos_helper.rb
module MaterialApoyosHelper
end

app/views/material_apoyo/_form.html.haml
= form_tag({:action => 'create'}, :multipart => true) do

  %fieldset
    %legend Carga de Archivo:

    %label Seleccione el archivo a importar:
    = file_field 'archivo', 'datafile', {:required => true, :class => 'btn'}

  %fieldset
    = "Selecione Cursos a los cuales quiere que esté disponible este material"
    %table.likert
      %thead
        %tr
          %th Curso
          %th

      %tbody
        - @cursos.each do |curso|
          %tr
            %td= curso.descripcion
            %td= check_box_tag "curso_ids[#{curso.id}]", true
  .actions
    = submit_tag 'Save', {:class => 'btn btn-success', :disable_with => "Cargando..."}

app/views/material_apoyo/edit.html.haml
%h1 Editing material_apoyo

= render 'form'

= link_to 'Show', @material_apoyo
\|
= link_to 'Back', :back

app/views/material_apoyo/index.html.haml
%h1 Listing material_apoyos

%table.likert
  %thead
    %tr
      %th Nombre
      %th.raw3 Url
      %th Tipo material apoyo
      %th
      %th
      %th

  - @material_apoyos.each do |material_apoyo|
    %tbody
      %tr.well
        %td.well= material_apoyo.nombre
        %td.well= material_apoyo.url
        %td.well= material_apoyo.tipo_material_apoyo.descripcion
        %td.well= link_to 'Show', material_apoyo
        %td.well= link_to 'Edit', edit_material_apoyo_path(material_apoyo)
        %td.well= link_to 'Destroy', material_apoyo, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Material apoyo', new_material_apoyo_path

app/views/material_apoyo/new.html.haml
%h1 Nuevo material de apoyo

= render 'form'

= link_to "Atrás", {:action => "index"}

app/views/material_apoyo/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @material_apoyo.nombre
%p
  %b Url:
  = @material_apoyo.url
%p
  %b Tipo material apoyo:
  = @material_apoyo.tipo_material_apoyo

= link_to 'Edit', edit_material_apoyo_path(@material_apoyo)
\|
= link_to 'Back', material_apoyos_path