config/routes.rb
Aceim::Application.routes.draw do

  resources :archivos

  resources :material_apoyo

  resources :tipo_actividades do
    resources :actividades
  end

  resources :parte_examenes do
    resources :parte_examen_actividades
  end

  resources :parte_examen_actividades do
    resources :actividades
  end

  resources :estudiante_examenes

  resources :examenes do
    resources :parte_examenes
    resources :estudiante_examenes
  end

  resources :actividades do
    resources :preguntas
    resources :textos
    resources :adjuntos    
  end

  resources :preguntas do
    resources :opciones
    resources :respuestas
  end

  resources :opciones

  resources :respuestas

  resources :textos

  resources :adjuntos

  resources :facturas do
    resources :detalle_facturas

    collection do
      get 'nueva'
      post 'actualizar'
      get 'registrar'
      get 'actualizar_idioma_select'
    end
  end
  

   root :to => 'inicio#index'
   
   

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/actividades_controller.rb
# encoding: utf-8

class ActividadesController < ApplicationController
  before_filter :filtro_logueado
  before_filter :filtro_administrador
  skip_before_filter  :verify_authenticity_token  

  # GET /actividades
  # GET /actividades.json
  def index
    @actividades = Actividad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @actividades }
    end
  end

  # GET /actividads/1
  # GET /actividads/1.json
  def show
    @actividad = Actividad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @actividad }
    end
  end

  # GET /actividads/new
  # GET /actividads/new.json
  def new
    @actividad = Actividad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @actividad }
    end
  end

  # GET /actividads/1/edit
  def edit
    @actividad = Actividad.find(params[:id])
  end

  # POST /actividads
  # POST /actividads.json
  def create
    1/0
    if params[:parte_examen_id]
      @parte_examen = ParteExamen.find(params[:parte_examen_id])
      @actividad = @parte_examen.actividades.create(params[:actividad])
    else
      @actividad = Actividad.new(params[:actividad])      
    end
    respond_to do |format|
      if @actividad.save
        # if params[:examen_id]
          flash[:mensaje] = 'Actividad creado con éxito.'
          format.html { redirect_to :controller => "admin_examenes", :action => "wizard_paso2", :id => @examen.id}
        # else
          # format.html { redirect_to examen_path(@examen), :notice => 'actividad was successfully created.' }          

          format.json { render :json => @examen, :status => :created, :location => @examen }
      else
        # accion = params[:examen_id] ? "admin_examenes/wizard_paso2/#{@examen.id}" : 'new'
        format.html { render :action => 'new' }
        format.json { render :json => @actividad.errors, :status => :unprocessable_entity }
      end
    end
  end


  # def actualizar_actividad
  #   @actividad = Actividad.find(params[:id])
  #   if @actividad.update_attributes(params[:actividad])
  #     flash[:mensaje] = "Datos elementales de la actividad actualizados"
  #   else
  #     flash[:mensaje] = "No se pudo actualizar los datos de la actividad"
  #   end
  #   redirect_to :back
  # end

  # def eliminar_actividad
  #   @actividad = Actividad.find(params[:id])
  #   flash[:mensaje] = "Actividad Eliminada con éxito" if @actividad.destroy

  #   redirect_to :back
  # end



  # PUT /actividades/1
  # PUT /actividades/1.json
  def update

    @actividad = Actividad.find(params[:id])
    if @actividad.update_attributes(params[:actividad])
      info_bitacora "Usuario: #{session[:usuario].ci} actualizó datos elementales de la actividad #{@actividad.id} actualizados."
      flash[:mensaje] = "Instrucciones de la actividad actualizados"
    else
      flash[:mensaje] = "No se pudo actualizar los datos de la actividad"
    end
    redirect_to :back
  end

  # DELETE /actividades/1
  # DELETE /actividades/1.json
  def destroy
    @actividad = Actividad.find(params[:id])
    actividad_id = @actividad.id
    if @actividad.destroy
      info_bitacora "Usuario: #{session[:usuario].ci} eliminó actividad #{actividad_id}."
      flash[:mensaje] = "Actividad Eliminada con éxito" 
    end

    redirect_to :back 
  end
end

app/views/actividades/_adjuntar_archivo.html.haml
-# @host = "http://fundeim.human.ucv.ve/aceim/assets/examenes/"
- @host = "#{request.protocol}#{request.host_with_port}/aceim/assets/examenes/"

- @actividad.adjuntos.each do |adjunto|
	.factura.well{:style => 'color:black;'}
		- ext = adjunto.archivo.split('.').last
		- imagenes = ['png', 'jpeg', 'jpg']
		- audios = ['mp3', 'mpeg', 'ogg', 'wav']
		.well.small
			- if imagenes.include? ext
				- if @editable 
					= link_to 'Eliminar Esta Imagen Adjunta', adjunto, :confirm => '¿Está Seguro?', :method => :delete, :class => 'btn_eliminar small flotar_derecha'
				= image_tag @host+adjunto.archivo, :style => 'padding: 0 130px; width: 70%;' 

			- elsif audios.include? ext
				- if @editable
					= link_to 'Eliminar Este Audio Adjunto', adjunto, :confirm => '¿Está Seguro?', :method => :delete, :class => ' btn_eliminar small flotar_derecha' 
				= audio_tag @host+adjunto.archivo, :class => "audio-play", :controls => true

			- else
				%h2
					= "Formato Desconocido: #{adjunto.archivo}"
				- if @editable 
					= link_to 'Eliminar Archivo Adjunto', adjunto, :confirm => '¿Está Seguro?', :method => :delete, :class => 'btn_eliminar small flotar_derecha'


- if @editable
	.well
		= link_to 'Incluir Archivo (Audio/Imagen) Adjunto', 'javascript:void(0)' , :class => "btn_agregar small", :onclick => "$(form_archivo_#{@actividad.id}).show('slow'); $(this).remove();"

		%div{:id => "form_archivo_#{@actividad.id}", :style => 'display:none;'}
			= render 'adjuntos/importar'

	%br

app/views/actividades/_form.html.haml
= form_for @actividad do |f|
  -if @actividad.errors.any?
    #error_explanation
      %h2= "#{pluralize(@actividad.errors.count, "error")} prohibited this actividad from being saved:"
      %ul
        - @actividad.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :titulo
    = f.text_field :titulo
  .field
    = f.label :tipo_segmento_id
    = f.text_field :tipo_segmento_id
  .field
    = f.label :curso_idioma_id
    = f.text_field :curso_idioma_id
  .field
    = f.label :curso_tipo_categoria_id
    = f.text_field :curso_tipo_categoria_id
  .field
    = f.label :curso_tipo_nivel_id
    = f.text_field :curso_tipo_nivel_id
  .actions
    = f.submit 'Save'

app/views/actividades/_form_actualizar_actividad.html.haml
%div{:id => "actualizar_actividad_#{@actividad.id}", :style => 'display:none;'}
  = form_tag({:controller => 'actividades',:action => "update", id: @actividad.id},{:method => 'put'}) do
    .well
      =# hidden_field_tag :id, @actividad.id
      %h2
        = text_field_tag 'actividad[instrucciones]', @actividad.instrucciones, :style => 'width: 100%;'
      %input.btn.small{:type => 'submit', :value => 'Actualizar Actividad', :name => 'commit'}

app/views/actividades/_incluir_texto.html.haml
-if @actividad.textos.count > 0
	.factura.well{:style => 'color:black;'}
		- @texto = @actividad.textos.first

		.well	
			%div
				= raw @texto.contenido
				- if @editable
					= link_to 'Editar Texto', 'javascript:void(0)' , :class => "btn_editar small", :onclick => "return editar_texto(#{@actividad.id}, this);"
		- if @editable
			
			%div{:id => "form_editar_texto_#{@actividad.id}", :style => 'display:none;'}
				= form_tag({:controller => "textos", :action => "actualizar"},{:class => 'form'}) do
					=hidden_field_tag "actividad_id", @actividad.id
					=#hidden_field_tag "examen_id", @examen_id
					=hidden_field_tag "texto_id", @actividad.textos.first.id

					%table
						%tr.req
							%td.derecha.separado
								%b= "*Contenido:"
							%td
								= text_area_tag :contenido, @actividad.textos.first.contenido, :style => 'width:600px;', :id => "contenido_texto_#{@actividad.id}"
							%td
								%input.btn_agregar.small{:type => 'submit', :value => 'Actualizar texto', :name => 'commit'}
- elsif @editable
	.well
		= link_to 'Agregar Texto', 'javascript:void(0)' , :class => "btn_agregar small", :onclick => "$(form_texto_#{@actividad.id}).show('slow'); $(this).remove();"
		%div{:id => "form_texto_#{@actividad.id}", :style => 'display:none;'}

			= form_for(@actividad.textos.build, {:url=>{:controller => 'textos',:action => "create"},:html => {:class => 'form'}}) do |f|
				=hidden_field_tag "actividad_id", @actividad.id
				=#hidden_field_tag "examen_id", @examen_id
				%table
					%tr.req
						%td.derecha.separado
							%b= "*Contenido:"
						%td
							= f.text_area :contenido, :class => :texto, :required => true, :style => 'width:600px;'
						%td
							%input.btn_agregar.small{:type => 'submit', :value => 'Agregar Texto', :name => 'commit'}
%br

app/views/actividades/_preguntas.html.haml
- @preguntas = @actividad.preguntas
- #if @preguntas.count > 0   
%h2= "Preguntas/Ítems:"
- case @actividad.tipo_actividad_id 
  - when 'SEL_MULTIPLE' 
    =render :partial => '/preguntas/lista_sel_multiple'
    =render :partial => '/preguntas/form_sel_multiple' if @editable
  - when 'COMPLETE_ESPACIO'
    =render :partial => '/preguntas/lista_completar_espacios'
    =render :partial => '/preguntas/form_completar_espacios' if @editable
  -else
    =render :partial => '/preguntas/lista_general'
    =render :partial => '/preguntas/form_general' if @editable

app/views/actividades/_wizard_form.html.haml
.well.factura
	%h3= "Agregar Datos del Esquema General de la Actividad:"
	=# form_for([:action => 'registrar_actividad', parte_examen.actividades.build]) do |f|
	= form_for(parte_examen.actividades.build,{:url=>{:action => "registrar_actividad"}, :html => {:class => 'form'}}) do |f|
		= f.hidden_field :curso_idioma_id, :value => @examen.curso_idioma_id
		= f.hidden_field :curso_tipo_categoria_id, :value => @examen.curso_tipo_categoria_id
		= f.hidden_field :curso_tipo_nivel_id, :value => @examen.curso_tipo_nivel_id
		= hidden_field_tag 'parte_examen[parte_id]', parte_examen.parte_id
		= hidden_field_tag 'parte_examen[examen_id]', parte_examen.examen_id	
		%table
			%tr.req
				%td.derecha.separado
					%b= "*Instrucciones:"
				%td
					= f.text_field :instrucciones, :style => 'width: 700px;', :required => true
			%tr.req
				%td.derecha.separado
					%b= "*Tipo de Actividad:"
				%td
					= f.collection_select :tipo_actividad_id, TipoActividad.all, :id, :descripcion, :prompt => true
			%tr
				%td
				%td
					%input.btn.small{:type => 'submit', :value => 'Agregar actividad', :name => 'commit'}

app/views/actividades/_wizard_list.html.haml
-#@editable = action_name!='presentar' or (controller_name.eql? 'examenes' and action_name!='show')
-@editable = (action_name.eql? 'wizard_paso2' or (controller_name.eql? 'actividades' and action_name.eql? 'show'))

.division_actividad
	%p{ :class => "ui-state-highlight ui-corner-all", :style => "margin-top: 20px; padding: 3px 3px" }
		%span.ui-icon.ui-icon-info{ :style =>"display:inline-block;" }
		%b="#{pluralize(@actividad.total_respuestas_esperadas, 'Respuesta esperada', 'Respuestas esperadas')} en esta actividad."
	%p
		%b{:style => 'color:yellow;'}= "#{@i} .- "
		%b= @actividad.descripcion_sin_tipo

	- if @editable
		%p
			=link_to 'Editar Actividad', 'javascript:void(0)' , :class => "small btn_editar", :onclick => "$(actualizar_actividad_#{@actividad.id}).show('slow'); $(this).parent().remove();"
			=link_to 'Eliminar Actividad', @actividad, :confirm => '¿Está Seguro?', :method => :delete, :class => "btn_eliminar small flotar_derecha"
			=render :partial => '/actividades/form_actualizar_actividad'

	=render :partial => '/actividades/incluir_texto'

	=render :partial => '/actividades/adjuntar_archivo'

	.factura.well{:style => 'color:black;'}
		=#Preguntas
		=render :partial => '/actividades/preguntas'
.division
%br

app/views/actividades/edit.html.haml
%h1 Editando Actividad

= render 'form'

= link_to 'Show', @segmento
\|
= link_to 'Back', segmentos_path

app/views/actividades/index.html.haml
%h1 Listing Actividades

Filtrar Contenido: 
=text_field_tag "filtro"
%table.tablesorter.tablefilter.likert
  %thead
    %tr
      %th Id
      %th{:style => 'width:40%;'} Instrucciones
      %th Tipo Actividad
      %th Partes
      %th Curso
      %th Opciones

  %tbody
    - @actividades.each do |actividad|
      %tr
        %td= actividad.id
        %td= actividad.instrucciones
        %td= actividad.tipo_actividad.descripcion
        %td
          - actividad.parte_examenes.each do |pe|
            = pe.parte.nombre 
        %td= actividad.curso.descripcion if actividad.curso
        %td
          = link_to 'Ver', actividad
          |
          =# link_to 'Editar', edit_actividad_path(actividad)
          = link_to 'Eliminar', actividad, :confirm => '¿Está Seguro?', :method => :delete

%br

= link_to 'New Actividad', new_actividad_path

app/views/actividades/new.html.haml
%h1 Nueva Actividad

= render 'form'

= link_to 'Regresar', actividades_path

app/views/actividades/show.html.haml
=javascript_include_tag "elrte.min.js"
=javascript_include_tag "/aceim/assets/elrte.min"

=link_to "Regresar", actividades_path, :class => 'btn_atras'

=render :partial => 'wizard_list'
%br
=link_to "Regresar", actividades_path, :class => 'btn_atras'

:javascript
  
  $("#parte").tabs();

  $( ".btn" ).button();
  
  $( ".btn_editar").button({
    icons: {
    primary: "ui-icon-pencil"
    }
  }); 
  
  $( ".btn_eliminar").button({
    icons: {
    primary: "ui-icon-trash"
    }
  });


  $( ".btn_previsualizar").button({
    icons: {
    primary: "ui-icon-arrow-4-diag "
    }
  });

  $( ".btn_atras").button({
    icons: {
    primary: "ui-icon-carat-1-w"
    }
  });

  $( ".btn_agregar").button({
    icons: {
    primary: "ui-icon-circle-plus"
    }
  });
  
  $( ".btn_remover").button({
    icons: {
    primary: " ui-icon-circle-minus"
    }
  }); 
  
  $( ".radio" ).buttonset();

  $(".form").validate();

  function eliminar_pregunta(id, actividad_id){
    return $.get("/aceim/preguntas/"+"?data-method=delete",   
      function(data){ alert("Data: " + data + "\nStatus: " + status);} );
  };

  function editar_texto(actividad_id, div){
    var opts = {
      absoluteURLs: false,
      cssClass : 'el-rte',
      lang     : 'es',
      width    : 600,
      height   : 350,
      toolbar  : 'maxi' // Se pueden usar las siguientes opciones: 'maxi',tiny', 'compact', 'normal'
    }

    $('#form_editar_texto_'+actividad_id).show('slow');
    $('#form_editar_texto_'+actividad_id).addClass('well');

    $('#contenido_texto_'+actividad_id).elrte(opts);
    $(div).parent().parent().remove();

  };